/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRightsRouteImport } from './routes/tenant-rights'
import { Route as ShelterRouteImport } from './routes/shelter'
import { Route as SearchV2RouteImport } from './routes/search-v2'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedSheltersRouteImport } from './routes/saved-shelters'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as HomeV2RouteImport } from './routes/home-v2'
import { Route as BasicNeedsRouteImport } from './routes/basic-needs'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'

const TenantRightsRoute = TenantRightsRouteImport.update({
  id: '/tenant-rights',
  path: '/tenant-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelterRoute = ShelterRouteImport.update({
  id: '/shelter',
  path: '/shelter',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchV2Route = SearchV2RouteImport.update({
  id: '/search-v2',
  path: '/search-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSheltersRoute = SavedSheltersRouteImport.update({
  id: '/saved-shelters',
  path: '/saved-shelters',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeV2Route = HomeV2RouteImport.update({
  id: '/home-v2',
  path: '/home-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicNeedsRoute = BasicNeedsRouteImport.update({
  id: '/basic-needs',
  path: '/basic-needs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/basic-needs': typeof BasicNeedsRoute
  '/home-v2': typeof HomeV2Route
  '/our-story': typeof OurStoryRoute
  '/saved-shelters': typeof SavedSheltersRoute
  '/search': typeof SearchRoute
  '/search-v2': typeof SearchV2Route
  '/shelter': typeof ShelterRoute
  '/tenant-rights': typeof TenantRightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/basic-needs': typeof BasicNeedsRoute
  '/home-v2': typeof HomeV2Route
  '/our-story': typeof OurStoryRoute
  '/saved-shelters': typeof SavedSheltersRoute
  '/search': typeof SearchRoute
  '/search-v2': typeof SearchV2Route
  '/shelter': typeof ShelterRoute
  '/tenant-rights': typeof TenantRightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/basic-needs': typeof BasicNeedsRoute
  '/home-v2': typeof HomeV2Route
  '/our-story': typeof OurStoryRoute
  '/saved-shelters': typeof SavedSheltersRoute
  '/search': typeof SearchRoute
  '/search-v2': typeof SearchV2Route
  '/shelter': typeof ShelterRoute
  '/tenant-rights': typeof TenantRightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/basic-needs'
    | '/home-v2'
    | '/our-story'
    | '/saved-shelters'
    | '/search'
    | '/search-v2'
    | '/shelter'
    | '/tenant-rights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/basic-needs'
    | '/home-v2'
    | '/our-story'
    | '/saved-shelters'
    | '/search'
    | '/search-v2'
    | '/shelter'
    | '/tenant-rights'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/basic-needs'
    | '/home-v2'
    | '/our-story'
    | '/saved-shelters'
    | '/search'
    | '/search-v2'
    | '/shelter'
    | '/tenant-rights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  BasicNeedsRoute: typeof BasicNeedsRoute
  HomeV2Route: typeof HomeV2Route
  OurStoryRoute: typeof OurStoryRoute
  SavedSheltersRoute: typeof SavedSheltersRoute
  SearchRoute: typeof SearchRoute
  SearchV2Route: typeof SearchV2Route
  ShelterRoute: typeof ShelterRoute
  TenantRightsRoute: typeof TenantRightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant-rights': {
      id: '/tenant-rights'
      path: '/tenant-rights'
      fullPath: '/tenant-rights'
      preLoaderRoute: typeof TenantRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelter': {
      id: '/shelter'
      path: '/shelter'
      fullPath: '/shelter'
      preLoaderRoute: typeof ShelterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-v2': {
      id: '/search-v2'
      path: '/search-v2'
      fullPath: '/search-v2'
      preLoaderRoute: typeof SearchV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-shelters': {
      id: '/saved-shelters'
      path: '/saved-shelters'
      fullPath: '/saved-shelters'
      preLoaderRoute: typeof SavedSheltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-v2': {
      id: '/home-v2'
      path: '/home-v2'
      fullPath: '/home-v2'
      preLoaderRoute: typeof HomeV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-needs': {
      id: '/basic-needs'
      path: '/basic-needs'
      fullPath: '/basic-needs'
      preLoaderRoute: typeof BasicNeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  BasicNeedsRoute: BasicNeedsRoute,
  HomeV2Route: HomeV2Route,
  OurStoryRoute: OurStoryRoute,
  SavedSheltersRoute: SavedSheltersRoute,
  SearchRoute: SearchRoute,
  SearchV2Route: SearchV2Route,
  ShelterRoute: ShelterRoute,
  TenantRightsRoute: TenantRightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
